// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgUAUAuvpi6_sOqXgOqz0sJ13U6nE2yQU',
    appId: '1:455762911:web:d3203f51d7552cbe665a6a',
    messagingSenderId: '455762911',
    projectId: 'staff-ticket-app',
    authDomain: 'staff-ticket-app.firebaseapp.com',
    storageBucket: 'staff-ticket-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH30UYcBDK_C67RqiMcE9wl7PdDPE0mtA',
    appId: '1:455762911:android:9d91a916551a2d83665a6a',
    messagingSenderId: '455762911',
    projectId: 'staff-ticket-app',
    storageBucket: 'staff-ticket-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK7cfGVTyUlJHBzstSmwn_pNZZ5BlHQLs',
    appId: '1:455762911:ios:8f36712717a434ee665a6a',
    messagingSenderId: '455762911',
    projectId: 'staff-ticket-app',
    storageBucket: 'staff-ticket-app.appspot.com',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK7cfGVTyUlJHBzstSmwn_pNZZ5BlHQLs',
    appId: '1:455762911:ios:8f36712717a434ee665a6a',
    messagingSenderId: '455762911',
    projectId: 'staff-ticket-app',
    storageBucket: 'staff-ticket-app.appspot.com',
    iosBundleId: 'com.example.adminDashboard',
  );
}
